"""Shared type-only primitives used by generated Graaly modules."""

from typing import Protocol, TypeVar

T_co = TypeVar("T_co", covariant=True)


class ApiObject(Protocol):
    """Type-only marker for an object adapted to the Python API surface."""
    ...


class NativeFuture(Protocol[T_co]):
    cancelled: bool
    done: bool
    def cancel(self, may_interrupt_if_running: bool = False) -> bool: ...
    def get(self) -> T_co: ...


class NativeRandom(Protocol):
    def next_int(self, bound: int | None = None) -> int: ...
    def next_long(self) -> int: ...
    def next_float(self) -> float: ...
    def next_double(self) -> float: ...
    def next_boolean(self) -> bool: ...


class NativeUuid(Protocol):
    def to_string(self) -> str: ...


class NativePath(Protocol):
    name: str
    path: str
    absolute_path: str
    def exists(self) -> bool: ...
    def is_file(self) -> bool: ...
    def is_directory(self) -> bool: ...


class NativeDate(Protocol):
    time: int
    def before(self, other: "NativeDate") -> bool: ...
    def after(self, other: "NativeDate") -> bool: ...


class NativeLogger(Protocol):
    def info(self, message: str) -> None: ...
    def warning(self, message: str) -> None: ...
    def severe(self, message: str) -> None: ...


class NativeThread(Protocol):
    name: str
    alive: bool
    def interrupt(self) -> None: ...
