import type { Challenge, Json } from "./types.ts";
const schema=`CREATE TABLE players(id INTEGER PRIMARY KEY, name TEXT NOT NULL, coins INTEGER NOT NULL CHECK(coins>=0));
CREATE TABLE items(sku TEXT PRIMARY KEY, price INTEGER NOT NULL, stock INTEGER NOT NULL CHECK(stock>=0));
CREATE TABLE orders(id INTEGER PRIMARY KEY, player_id INTEGER REFERENCES players(id), sku TEXT, quantity INTEGER NOT NULL, total INTEGER NOT NULL, created INTEGER NOT NULL);
CREATE TABLE ledger(id INTEGER PRIMARY KEY, player_id INTEGER REFERENCES players(id), delta INTEGER NOT NULL);
CREATE TABLE outbox(id INTEGER PRIMARY KEY, aggregate_id TEXT, seq INTEGER, delivered INTEGER NOT NULL DEFAULT 0);
CREATE TABLE memberships(player_id INTEGER REFERENCES players(id), party TEXT, UNIQUE(player_id,party));`;
function sql(id:string,title:string,solution:string,rules:string[],cases:[Json,Json][],why:string,hard=false):Challenge {
  return {id,number:0,title,track:"SQL / persistence",difficulty:hard?"Hard":"Medium",mode:"sql",tags:["SQLite","SQL","transactions"],modules:["config"],lessons:[25,31,35],description:["Write executable SQLite SQL for the plugin backend. Every test starts an isolated in-memory database with the supplied schema and fixture rows."],requirements:rules,inputType:schema,
    starters:{sql:"-- TODO: implement the required query or transaction.\nSELECT 1 AS todo;\n"},solutions:{sql:solution+"\n"},sqlSchema:schema,
    cases:cases.map(([input,expected],index)=>({name:index?"Database edge "+index:"Example database",input,expected,hidden:index>0})),hints:[rules[0],"Account for NULL and missing related rows, not just records present in every table.","Order the final result explicitly; SQL row order is not implicit."],explanation:[why,"The judge executes your SQL against SQLite, including constraints and transaction behavior. Result rows are compared by named columns and the explicitly required order."],complexity:"Depends on the query plan, input cardinality and indexes. Check joins and ordering when moving to the production database.",pitfalls:["Bind supplied parameters by name; do not concatenate client values into SQL."]};
}
export const sqlProblems=[
sql("sql-player-balances","Order a leaderboard with deterministic ties","SELECT name,coins FROM players ORDER BY coins DESC,name ASC;",["Return name,coins in descending coins order, then ascending name."],[[{setup:"INSERT INTO players VALUES(1,'B',10),(2,'A',10),(3,'C',2);"},[{name:"A",coins:10},{name:"B",coins:10},{name:"C",coins:2}]],[{setup:""},[]],[{setup:"INSERT INTO players VALUES(1,'Zero',0);"},[{name:"Zero",coins:0}]]],"A deterministic secondary key keeps repeated leaderboard pages stable when scores tie."),
sql("sql-zero-purchases","Keep players who have never purchased","SELECT p.name,COALESCE(SUM(o.quantity),0) AS purchased FROM players p LEFT JOIN orders o ON o.player_id=p.id GROUP BY p.id,p.name ORDER BY p.name;",["Return each player name and purchased quantity, including zero purchases.","Order by name."],[[{setup:"INSERT INTO players VALUES(1,'A',0),(2,'B',0);INSERT INTO orders VALUES(1,1,'stone',3,9,0),(2,1,'book',2,8,1);"},[{name:"A",purchased:5},{name:"B",purchased:0}]],[{setup:"INSERT INTO players VALUES(1,'A',0);"},[{name:"A",purchased:0}]],[{setup:""},[]]],"A LEFT JOIN preserves the player domain while COALESCE converts a missing aggregate into the defined zero quantity."),
sql("sql-revenue","Aggregate shop revenue by SKU","SELECT sku,SUM(total) AS revenue,SUM(quantity) AS units FROM orders GROUP BY sku ORDER BY revenue DESC,sku;",["Return sku,revenue,units for purchased SKUs.","Sort revenue descending then SKU."],[[{setup:"INSERT INTO players VALUES(1,'A',0);INSERT INTO orders VALUES(1,1,'stone',2,6,0),(2,1,'stone',1,3,1),(3,1,'book',1,9,2);"},[{sku:"book",revenue:9,units:1},{sku:"stone",revenue:9,units:3}]],[{setup:""},[]],[{setup:"INSERT INTO players VALUES(1,'A',0);INSERT INTO orders VALUES(1,1,'free',2,0,0);"},[{sku:"free",revenue:0,units:2}]]],"Revenue and quantity are different measures. Group by SKU rather than an individual order to preserve their aggregate meaning."),
sql("sql-having","Filter aggregate spend after grouping","SELECT p.name,SUM(o.total) AS spent FROM players p JOIN orders o ON p.id=o.player_id GROUP BY p.id,p.name HAVING SUM(o.total)>=:minimum ORDER BY spent DESC,p.name;",["Return players whose total spent >= :minimum.","Output name,spent ordered descending spend then name."],[[{params:{minimum:10},setup:"INSERT INTO players VALUES(1,'A',0),(2,'B',0);INSERT INTO orders VALUES(1,1,'x',1,6,0),(2,1,'x',1,5,1),(3,2,'x',1,9,0);"},[{name:"A",spent:11}]],[{params:{minimum:0},setup:"INSERT INTO players VALUES(1,'A',0);"},[]],[{params:{minimum:10},setup:"INSERT INTO players VALUES(1,'A',0);INSERT INTO orders VALUES(1,1,'x',1,10,0);"},[{name:"A",spent:10}]]],"WHERE filters rows before aggregation; HAVING filters the resulting player groups after their complete spend has been calculated."),
sql("sql-latest-order","Read the latest order per player with a tie-break",`SELECT name,order_id,total FROM (SELECT p.name,o.id AS order_id,o.total,ROW_NUMBER() OVER(PARTITION BY p.id ORDER BY o.created DESC,o.id DESC) AS position FROM players p JOIN orders o ON p.id=o.player_id) WHERE position=1 ORDER BY name;`,["Return name,order_id,total of each purchasing player's latest order.","Higher order ID wins when created ticks tie."],[[{setup:"INSERT INTO players VALUES(1,'A',0),(2,'B',0);INSERT INTO orders VALUES(1,1,'x',1,4,10),(2,1,'x',1,9,10),(3,2,'x',1,2,3);"},[{name:"A",order_id:2,total:9},{name:"B",order_id:3,total:2}]],[{setup:"INSERT INTO players VALUES(1,'A',0);"},[]],[{setup:"INSERT INTO players VALUES(1,'A',0);INSERT INTO orders VALUES(9,1,'x',1,1,0),(1,1,'x',1,2,5);"},[{name:"A",order_id:1,total:2}]]],"A window rank selects a complete row under a total ordering. MAX(created) alone cannot tell which total or order ID belongs to the winning row.",true),
sql("sql-dense-rank","Rank tied coin balances without gaps","SELECT name,coins,DENSE_RANK() OVER(ORDER BY coins DESC) AS rank FROM players ORDER BY coins DESC,name;",["Return name,coins,rank.","Equal balances share a rank; the next rank has no gap."],[[{setup:"INSERT INTO players VALUES(1,'A',9),(2,'B',9),(3,'C',5);"},[{name:"A",coins:9,rank:1},{name:"B",coins:9,rank:1},{name:"C",coins:5,rank:2}]],[{setup:""},[]],[{setup:"INSERT INTO players VALUES(1,'A',0);"},[{name:"A",coins:0,rank:1}]]],"DENSE_RANK expresses score groups, while ROW_NUMBER assigns a different position to every row. The ordering for display can still include a name tie-break."),
sql("sql-stock-reservation","Reserve stock only when the complete amount fits","UPDATE items SET stock=stock-:quantity WHERE sku=:sku AND stock>=:quantity AND :quantity>0; SELECT sku,stock FROM items ORDER BY sku;",["Subtract positive :quantity from :sku only if enough stock exists.","Return every sku,stock ordered by SKU; a denied reserve changes nothing."],[[{params:{quantity:3,sku:"stone"},setup:"INSERT INTO items VALUES('stone',2,5);"},[{sku:"stone",stock:2}]],[{params:{quantity:6,sku:"stone"},setup:"INSERT INTO items VALUES('stone',2,5);"},[{sku:"stone",stock:5}]],[{params:{quantity:-1,sku:"stone"},setup:"INSERT INTO items VALUES('stone',2,5);"},[{sku:"stone",stock:5}]]],"The predicate and decrement belong to one statement, avoiding a read-then-write race and negative stock. Negative requests must not create stock.",true),
sql("sql-rollback","Roll back a tentative debit","BEGIN; UPDATE players SET coins=coins-:amount WHERE id=:player_id AND coins>=:amount; ROLLBACK; SELECT name,coins FROM players ORDER BY name;",["Perform a guarded tentative debit inside a transaction, then roll it back.","Return all original balances ordered by name."],[[{params:{amount:3,player_id:1},setup:"INSERT INTO players VALUES(1,'A',5);"},[{name:"A",coins:5}]],[{params:{amount:10,player_id:1},setup:"INSERT INTO players VALUES(1,'A',5);"},[{name:"A",coins:5}]],[{params:{amount:1,player_id:9},setup:""},[]]],"A rollback discards a tentative mutation regardless of whether the guarded update matched a row. Transaction boundaries are part of the resource lifecycle."),
sql("sql-ledger-reconciliation","Reconcile balances against the ledger","SELECT p.name,p.coins,COALESCE(SUM(l.delta),0) AS ledger FROM players p LEFT JOIN ledger l ON p.id=l.player_id GROUP BY p.id,p.name HAVING p.coins<>COALESCE(SUM(l.delta),0) ORDER BY p.name;",["Return only mismatched name,coins,ledger totals.","A missing ledger means zero."],[[{setup:"INSERT INTO players VALUES(1,'A',5),(2,'B',2);INSERT INTO ledger VALUES(1,1,10),(2,1,-5),(3,2,1);"},[{name:"B",coins:2,ledger:1}]],[{setup:"INSERT INTO players VALUES(1,'A',0);"},[]],[{setup:"INSERT INTO players VALUES(1,'A',3);"},[{name:"A",coins:3,ledger:0}]]],"Reconciliation compares two independently maintained views of the same domain amount. Missing history is a defined zero, not an invisible row.",true),
sql("sql-outbox-head","Publish only the next pending sequence per aggregate","SELECT o.id,o.aggregate_id,o.seq FROM outbox o WHERE o.delivered=0 AND NOT EXISTS(SELECT 1 FROM outbox earlier WHERE earlier.aggregate_id=o.aggregate_id AND earlier.delivered=0 AND earlier.seq<o.seq) ORDER BY o.aggregate_id,o.id;",["Return each aggregate's earliest undelivered sequence.","Delivered records do not block; output id,aggregate_id,seq ordered by aggregate then id."],[[{setup:"INSERT INTO outbox VALUES(1,'a',1,1),(2,'a',2,0),(3,'a',3,0),(4,'b',1,0);"},[{id:2,aggregate_id:"a",seq:2},{id:4,aggregate_id:"b",seq:1}]],[{setup:"INSERT INTO outbox VALUES(1,'a',1,1);"},[]],[{setup:"INSERT INTO outbox VALUES(2,'a',4,0),(1,'a',3,0);"},[{id:1,aggregate_id:"a",seq:3}]]],"An outbox preserves causal order within each aggregate while allowing unrelated aggregates to progress independently.",true),
sql("sql-party-overlap","Find players sharing at least two parties","SELECT p.name,COUNT(*) AS parties FROM players p JOIN memberships m ON p.id=m.player_id GROUP BY p.id,p.name HAVING COUNT(*)>=2 ORDER BY parties DESC,p.name;",["Return name,parties for players with at least two memberships.","Unique membership constraint prevents duplicate counting."],[[{setup:"INSERT INTO players VALUES(1,'A',0),(2,'B',0);INSERT INTO memberships VALUES(1,'x'),(1,'y'),(2,'x');"},[{name:"A",parties:2}]],[{setup:"INSERT INTO players VALUES(1,'A',0);INSERT INTO memberships VALUES(1,'x');"},[]],[{setup:""},[]]],"Membership uniqueness is enforced by the schema. Aggregate queries can rely on that invariant instead of trying to repair duplicated relationships later."),
sql("sql-running-revenue","Calculate a deterministic running revenue total","SELECT id,total,SUM(total) OVER(ORDER BY created,id ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS running FROM orders ORDER BY created,id;",["Output id,total,running ordered by created then id.","Use a row frame so tied ticks progress one order at a time."],[[{setup:"INSERT INTO players VALUES(1,'A',0);INSERT INTO orders VALUES(2,1,'x',1,7,0),(1,1,'x',1,3,0),(3,1,'x',1,2,1);"},[{id:1,total:3,running:3},{id:2,total:7,running:10},{id:3,total:2,running:12}]],[{setup:""},[]],[{setup:"INSERT INTO players VALUES(1,'A',0);INSERT INTO orders VALUES(1,1,'x',1,0,0);"},[{id:1,total:0,running:0}]]],"A ROWS frame and complete tie-break determine the running total per event. The default peer frame can group tied timestamps unexpectedly.",true),
];
