import { exercise } from "./author.ts";

export const coreProblems = [
  exercise({
    id: "command-tokenizer", title: "Quoted command arguments", track: "Commands", tags: ["parsing", "state machine"], modules: ["commands"],
    task: "A teleport command accepts names containing spaces. Write the argument tokenizer before registering the command with commands.on. Support double quotes and backslash escapes without losing an empty quoted argument.",
    rules: ["Whitespace separates arguments outside quotes.", "Backslash escapes the next character both inside and outside quotes.", "Return null for an unclosed quote or a trailing backslash.", "Preserve the empty argument in \"\"; empty input returns []."],
    input: "{ text: string }", body: `const out = []; let token = "", quoted = false, escaped = false, started = false;
for (const ch of input.text) {
  if (escaped) { token += ch; escaped = false; started = true; }
  else if (ch === "\\\\") { escaped = true; started = true; }
  else if (ch === '"') { quoted = !quoted; started = true; }
  else if (/\\s/.test(ch) && !quoted) { if (started) out.push(token); token = ""; started = false; }
  else { token += ch; started = true; }
}
if (quoted || escaped) return null;
if (started) out.push(token);
return out;`,
    examples: [[{ text: 'tp "Alex Smith" spawn' }, ["tp", "Alex Smith", "spawn"]], [{ text: 'say "" done' }, ["say", "", "done"]]],
    extra: [[{ text: "  " }, []], [{ text: 'tp "Alex' }, null], [{ text: "a\\ b c" }, ["a b", "c"]], [{ text: "a\\" }, null]],
    hints: ["Track whether you are inside a quote separately from the current token.", "An empty token may still be a real argument; keep a started flag.", "Flush only at unquoted whitespace, then check both unfinished states."],
    why: ["The tokenizer is a finite state machine. Quoted mode changes the meaning of whitespace; escaped mode changes the meaning of the next character.", "Token contents cannot tell you whether a token exists: an explicit empty quoted argument has zero characters. The started flag preserves that distinction before the command callback validates arity."], cost: "O(n) time and O(n) output space.", pitfalls: ["Splitting on spaces loses quotes and escapes.", "Dropping an empty quoted argument changes command arity."]
  }),
  exercise({ id: "permission-tree", title: "Most specific permission wins", track: "Commands", hard: true, tags: ["permissions", "prefixes"], modules: ["commands", "players"],
    task: "Implement a permission resolver for an admin command. Rules can grant or deny exact nodes or a subtree wildcard. A specific denial must beat a broad grant.",
    rules: ["'*' matches every node; 'shop.*' matches descendants of shop, not shop itself.", "Exact rules outrank wildcard rules; deeper wildcard prefixes outrank shallower ones.", "For equally specific rules, denial wins.", "Return false when no rule matches."], input: "{ node: string; rules: {node: string; allow: boolean}[] }",
    body: `let best = -1, result = false;
for (const rule of input.rules) {
  const wildcard = rule.node.endsWith(".*");
  const prefix = wildcard ? rule.node.slice(0, -1) : "";
  const matches = rule.node === "*" || rule.node === input.node || (wildcard && input.node.startsWith(prefix));
  if (!matches) continue;
  const rank = rule.node === "*" ? 0 : wildcard ? prefix.split(".").length * 2 : input.node.split(".").length * 2 + 1;
  if (rank > best) { best = rank; result = rule.allow; }
  else if (rank === best) result = result && rule.allow;
}
return result;`,
    examples: [[{ node: "shop.buy", rules: [{ node: "*", allow: true }, { node: "shop.buy", allow: false }] }, false], [{ node: "shop.admin.reset", rules: [{ node: "shop.*", allow: false }, { node: "shop.admin.*", allow: true }] }, true]],
    extra: [[{ node: "shop", rules: [{ node: "shop.*", allow: true }] }, false], [{ node: "x", rules: [] }, false], [{ node: "shop.buy", rules: [{ node: "shop.buy", allow: false }, { node: "shop.buy", allow: true }] }, false]],
    hints: ["Calculate a specificity rank instead of returning on the first match.", "Require the separator after a subtree prefix.", "Resolve a rank tie with logical AND."],
    why: ["Permission resolution is independent of configuration order. Assign an exact rule a higher rank than the wildcard at the same depth, then retain only the best rank.", "A denial at equal rank is a deliberate fail-closed policy. Matching a dotted prefix also prevents shop.* from accidentally granting shopping.admin."], cost: "O(r × d) time for r rules and node length d; O(1) additional space." }),
  exercise({ id: "command-completion", title: "Permission-aware tab completion", track: "Commands", tags: ["commands", "deduplication"], modules: ["commands"],
    task: "Build command suggestions from an operator's permitted subcommands. Never expose a restricted name, and make completion deterministic.",
    rules: ["Match the prefix case-insensitively.", "A command is visible if permission is null or present in granted.", "Deduplicate names case-insensitively, preserving the first spelling.", "Sort by lowercase spelling and return at most limit names."], input: "{ prefix: string; granted: string[]; limit: number; commands: {name:string; permission:string|null}[] }",
    body: `const seen = new Set(), out = [];
for (const command of input.commands) {
  const key = command.name.toLowerCase();
  if (!key.startsWith(input.prefix.toLowerCase()) || seen.has(key)) continue;
  if (command.permission !== null && !input.granted.includes(command.permission)) continue;
  seen.add(key); out.push(command.name);
}
return out.sort((a,b) => a.toLowerCase().localeCompare(b.toLowerCase(), "en")).slice(0, Math.max(0,input.limit));`,
    examples: [[{ prefix: "re", granted: ["admin"], limit: 4, commands: [{name:"reset",permission:"admin"},{name:"reload",permission:null},{name:"remove",permission:"owner"}] }, ["reload","reset"]], [{ prefix:"",granted:[],limit:1,commands:[{name:"help",permission:null},{name:"HELP",permission:null},{name:"buy",permission:null}] }, ["buy"]]],
    extra: [[{prefix:"x",granted:[],limit:5,commands:[]},[]], [{prefix:"",granted:[],limit:0,commands:[{name:"a",permission:null}]},[]]],
    hints:["Filter authorization before adding to the seen set.","Normalize only the comparison key; keep the original label.","Apply the limit after sorting."], why:["Completion is a public API surface: authorization belongs in the filter just as it does in the command handler.","Keeping a normalized identity separate from presentation avoids duplicate suggestions while retaining intentional spelling."],cost:"O(n log n) time and O(n) space." }),
  exercise({id:"cooldown-command", title:"A command with an exact cooldown",track:"Commands",tags:["plugin","cooldown"],modules:["commands","players"],mode:"plugin",imports:'import { commands, players } from "graaly";',
    task:"Register /heal. Only players with heal.use can heal, and each player has an independent cooldown measured in ticks. The scenario drives the real command callback shape with a deterministic clock.",
    rules:["Console replies 'Players only'. Missing permission replies 'Denied'.", "Successful healing sets health to 20 and replies 'Healed'.", "A second use before input.cooldown ticks replies 'Cooldown'.", "input.now() supplies the current scenario tick. Exact expiry is allowed; denied calls do not consume cooldown."],input:"{ cooldown:number; now:()=>number } + scenario players/actions",
    body:`const last = new Map();
commands.on("heal", context => {
  if (!players.isPlayer(context.sender)) { context.reply("Players only"); return true; }
  if (!context.hasPermission("heal.use")) { context.reply("Denied"); return true; }
  const now = input.now(), previous = last.get(context.sender.name);
  if (previous !== undefined && now - previous < input.cooldown) { context.reply("Cooldown"); return true; }
  last.set(context.sender.name, now); context.sender.health = 20; context.reply("Healed"); return true;
});`,
    examples:[[{cooldown:10,players:[{name:"Alex",health:5,permissions:["heal.use"]}],actions:[{kind:"command",name:"heal",sender:"Alex",tick:0},{kind:"command",name:"heal",sender:"Alex",tick:9},{kind:"command",name:"heal",sender:"Alex",tick:10}]},[["health","Alex",20],["message","Alex","Healed"],["message","Alex","Cooldown"],["health","Alex",20],["message","Alex","Healed"]]]],
    extra:[[{cooldown:3,players:[{name:"Alex",permissions:[]}],actions:[{kind:"command",name:"heal",sender:"Alex",tick:0},{kind:"command",name:"heal",sender:"CONSOLE",tick:1}]},[["message","Alex","Denied"],["message","CONSOLE","Players only"]]], [{cooldown:5,players:[{name:"Alex",permissions:["heal.use"]},{name:"Sam",permissions:["heal.use"]}],actions:[{kind:"command",name:"heal",sender:"Alex",tick:0},{kind:"command",name:"heal",sender:"Sam",tick:0}]},[["health","Alex",20],["message","Alex","Healed"],["health","Sam",20],["message","Sam","Healed"]]]],
    hints:["Use players.isPlayer before accessing player health.","Keep a Map keyed by player identity, not one global last-use time.","Compare with '< cooldown'; do not treat tick zero as a missing timestamp."],why:["The callback authorizes before performing any mutation. Each accepted action records the deterministic current tick, so one player's activity cannot block another player.","A stored timestamp of zero is valid. Checking previous !== undefined and allowing equality at the expiry tick makes the boundary test precise."],cost:"O(1) expected work per command; O(p) cooldown storage."}),
  exercise({id:"alias-cycles",title:"Resolve command aliases without cycles",track:"Commands",hard:true,tags:["graphs","cycle detection"],modules:["commands"],task:"Operators can alias one command to another. Resolve each requested alias to its terminal command, or report null if that chain cycles.",rules:["A command absent from aliases is terminal.","A self-alias is a cycle.","Return one resolution per requested name in the original order."],input:"{ aliases: Record<string,string>; names: string[] }",body:`return input.names.map(name => {
  const seen = new Set();
  while (Object.hasOwn(input.aliases,name)) {
    if (seen.has(name)) return null;
    seen.add(name); name = input.aliases[name];
  }
  return name;
});`,examples:[[{aliases:{h:"heal",med:"h"},names:["med","spawn"]},["heal","spawn"]]],extra:[[{aliases:{a:"b",b:"a",c:"a"},names:["a","b","c"]},[null,null,null]],[{aliases:{a:"a"},names:["a","x"]},[null,"x"]],[{aliases:{},names:[]},[]]],hints:["Traverse outgoing edges until no edge remains.","A visited set belongs to one traversal.","Check for revisiting before taking the next edge."],why:["Alias definitions form a directed graph with at most one outgoing edge per node. Every walk either reaches a terminal node or revisits a node.","The per-walk visited set catches cycles even when a requested alias merely leads into the cycle rather than belonging to it."],cost:"O(q × a) worst-case time and O(a) space."}),
  exercise({id:"command-usage-parser",title:"Validate ranged numeric arguments",track:"Commands",tags:["validation","boundary checks"],modules:["commands"],task:"Parse a /give count without accepting partial numbers, exponent notation or overflow. Return a normalized integer or an explicit error.",rules:["Trim surrounding whitespace; accept only an optional '+' followed by decimal digits.","The result must be a safe integer in the inclusive [min,max] range.","Return {ok:true,value} or {ok:false,error:'syntax'|'range'}."],input:"{ value:string; min:number; max:number }",body:`const text = input.value.trim();
if (!/^\\+?\\d+$/.test(text)) return {ok:false,error:"syntax"};
const value = Number(text);
if (!Number.isSafeInteger(value) || value < input.min || value > input.max) return {ok:false,error:"range"};
return {ok:true,value};`,examples:[[{value:" +064 ",min:1,max:64},{ok:true,value:64}],[{value:"3items",min:1,max:64},{ok:false,error:"syntax"}]],extra:[[{value:"1e2",min:1,max:1000},{ok:false,error:"syntax"}],[{value:"0",min:1,max:64},{ok:false,error:"range"}],[{value:"9007199254740993",min:0,max:1e20},{ok:false,error:"range"}]],hints:["parseInt accepts valid prefixes of invalid arguments.","Validate the entire string before conversion.","Check safe-integer precision separately from the configured bounds."],why:["Command text is an untrusted protocol boundary. A full-string grammar rejects trailing garbage before numeric conversion.","JavaScript numbers cannot represent every large integer exactly. Number.isSafeInteger prevents a rounded value from passing the policy check."],cost:"O(n) time, O(n) trimmed string space."}),
  exercise({id:"event-priorities",title:"Deterministic event priority pipeline",track:"Events",tags:["events","ordering"],modules:["events"],task:"Model event listener ordering before implementing an event pipeline. Higher-level cancellation must affect subsequent ignoreCancelled listeners.",rules:["Run LOWEST, LOW, NORMAL, HIGH, HIGHEST, MONITOR in that order; retain registration order for ties.","A listener with ignoreCancelled skips an already cancelled event.","A listener's cancel field, when boolean, sets cancellation after it runs.","Return {ran:string[],cancelled:boolean}."],input:"{ cancelled:boolean; listeners:{id:string;priority:string;ignoreCancelled:boolean;cancel?:boolean}[] }",body:`const order = ["LOWEST","LOW","NORMAL","HIGH","HIGHEST","MONITOR"];
const listeners = input.listeners.map((listener,index)=>({...listener,index})).sort((a,b)=>order.indexOf(a.priority)-order.indexOf(b.priority)||a.index-b.index);
let cancelled = input.cancelled; const ran = [];
for (const listener of listeners) {
  if (cancelled && listener.ignoreCancelled) continue;
  ran.push(listener.id);
  if (typeof listener.cancel === "boolean") cancelled = listener.cancel;
}
return {ran,cancelled};`,examples:[[{cancelled:false,listeners:[{id:"late",priority:"HIGH",ignoreCancelled:true},{id:"guard",priority:"LOW",ignoreCancelled:false,cancel:true}]},{ran:["guard"],cancelled:true}]],extra:[[{cancelled:true,listeners:[{id:"audit",priority:"MONITOR",ignoreCancelled:false},{id:"restore",priority:"NORMAL",ignoreCancelled:false,cancel:false},{id:"next",priority:"HIGH",ignoreCancelled:true}]},{ran:["restore","next","audit"],cancelled:false}],[{cancelled:false,listeners:[]},{ran:[],cancelled:false}]],hints:["Decorate each registration with its original index.","Read the current cancellation flag inside the loop.","Skipping a listener means skipping its mutation too."],why:["Listener order is a stable priority sort, but cancellation is dynamic state rather than a filter that can be applied once before the loop.","The explicit original index documents deterministic tie handling and makes behavior independent of how the sorting implementation treats equal elements."],cost:"O(n log n) time, O(n) space."}),
  exercise({id:"join-welcome-plugin",title:"Welcome only first-time joins",track:"Events",tags:["plugin","join events"],modules:["events","players"],mode:"plugin",imports:'import { events, PlayerJoinEvent } from "graaly";',task:"Register a PlayerJoinEvent callback that welcomes a first-time player. A repeated callback for the same player during this enable cycle must not duplicate the welcome.",rules:["Only players with hasPlayedBefore === false get 'Welcome <name>'.","Deduplicate by uniqueId, not display name.","Returning players produce no trace."],input:"scenario players/actions",body:`const welcomed = new Set();
events.on(PlayerJoinEvent, event => {
  const player = event.player;
  if (player.hasPlayedBefore || welcomed.has(player.uniqueId)) return;
  welcomed.add(player.uniqueId); player.sendMessage("Welcome " + player.name);
});`,examples:[[{players:[{name:"Alex",uniqueId:"a",hasPlayedBefore:false}],actions:[{kind:"event",name:"PlayerJoinEvent",player:"Alex"},{kind:"event",name:"PlayerJoinEvent",player:"Alex"}]},[["message","Alex","Welcome Alex"]]]],extra:[[{players:[{name:"Sam",hasPlayedBefore:true}],actions:[{kind:"event",name:"PlayerJoinEvent",player:"Sam"}]},[]],[{players:[{name:"A",uniqueId:"a",hasPlayedBefore:false},{name:"B",uniqueId:"b",hasPlayedBefore:false}],actions:[{kind:"event",name:"PlayerJoinEvent",player:"A"},{kind:"event",name:"PlayerJoinEvent",player:"B"}]},[["message","A","Welcome A"],["message","B","Welcome B"]]]],hints:["Register the callback instead of processing actions yourself.","Store stable player UUIDs in a Set.","Mark a player before sending the side effect."],why:["A plugin registers behavior; the scenario then invokes the callback with Graaly's adapted event and player shapes.","Stable identity and an enable-scoped Set make the welcome idempotent even if the same event is delivered twice."],cost:"O(1) expected per event, O(p) space."}),
  exercise({id:"region-protection",title:"Overlapping region protection",track:"Events",hard:true,tags:["geometry","authorization"],modules:["events","worlds"],task:"Decide whether a block break is allowed inside overlapping cuboid regions. Every matching protected region must permit the player; permission in one region cannot override denial in another.",rules:["Corners can be given in either order and are inclusive.","Regions in a different world do not match.","An owner or member may break; otherwise that region denies.","Return sorted IDs of denying regions; [] means allowed."],input:"{ player:string; world:string; point:number[]; regions:{id:string;world:string;a:number[];b:number[];owner:string;members:string[]}[] }",body:`return input.regions.filter(region => region.world === input.world && region.a.every((a,i)=>input.point[i]>=Math.min(a,region.b[i])&&input.point[i]<=Math.max(a,region.b[i])) && region.owner !== input.player && !region.members.includes(input.player)).map(region=>region.id).sort();`,examples:[[{player:"a",world:"w",point:[0,5,0],regions:[{id:"outer",world:"w",a:[-1,0,-1],b:[1,10,1],owner:"b",members:[]},{id:"inner",world:"w",a:[1,10,1],b:[-1,0,-1],owner:"a",members:[]}]},["outer"]]],extra:[[{player:"a",world:"w",point:[0,0,0],regions:[{id:"other",world:"z",a:[0,0,0],b:[0,0,0],owner:"b",members:[]}]},[]],[{player:"a",world:"w",point:[1,1,1],regions:[{id:"r",world:"w",a:[0,0,0],b:[1,1,1],owner:"b",members:["a"]}]},[]]],hints:["Normalize each axis independently with min and max.","Separate region containment from region authorization.","Collect all denials instead of returning after the first grant."],why:["Spatial membership and authorization are separate predicates. Once every axis and the world match, the player must satisfy that region's access policy.","Intersecting protected regions combine through logical AND. The list of denying IDs makes the result explainable to a player and testable without a running server."],cost:"O(r + d log d) time for r regions and d denials; O(d) output space."}),
  exercise({id:"damage-pipeline",title:"Damage modifiers with a final clamp",track:"Events",tags:["reducers","combat"],modules:["events","entities"],task:"Apply a documented damage policy without changing the original modifier list. Additive and multiplicative modifiers run in their given order; clamp only the final result.",rules:["Start from input.damage.","{kind:'add',value} adds and {kind:'multiply',value} multiplies.","Return zero for a cancelled event.","Otherwise clamp the final value to [0, cap]; do not clamp intermediate values."],input:"{damage:number;cap:number;cancelled:boolean;modifiers:{kind:'add'|'multiply';value:number}[]}",body:`if (input.cancelled) return 0;
let value = input.damage;
for (const modifier of input.modifiers) value = modifier.kind === "add" ? value + modifier.value : value * modifier.value;
return Math.max(0,Math.min(input.cap,value));`,examples:[[{damage:10,cap:100,cancelled:false,modifiers:[{kind:"add",value:-20},{kind:"multiply",value:-2}]},20]],extra:[[{damage:10,cap:20,cancelled:true,modifiers:[]},0],[{damage:50,cap:20,cancelled:false,modifiers:[]},20],[{damage:1,cap:100,cancelled:false,modifiers:[{kind:"multiply",value:3},{kind:"add",value:2}]},5]],hints:["Keep the cancellation guard separate from calculation.","A reducer must respect modifier order.","A negative intermediate value can later become positive."],why:["The policy's order is observable: multiplication and addition do not commute. An imperative accumulator or reducer expresses the sequential transformation clearly.","Clamping once at the end matches the contract and avoids erasing an intermediate value that a later modifier should still see."],cost:"O(m) time, O(1) additional space."}),
  exercise({id:"event-idempotency",title:"Bounded duplicate-event window",track:"Events",hard:true,tags:["idempotency","sliding window"],modules:["events"],lessons:[25,35],task:"Consume event deliveries with an ID and timestamp. Ignore a duplicate only while its last accepted timestamp remains inside the TTL window.",rules:["Deliveries are in nondecreasing timestamp order.","A duplicate at exactly TTL age is accepted.","Rejected duplicates do not extend the expiry.","Return the indexes of accepted deliveries."],input:"{ttl:number;events:{id:string;at:number}[]}",body:`const last = new Map(), accepted = [];
input.events.forEach((event,index)=>{
  const previous = last.get(event.id);
  if (previous === undefined || event.at-previous >= input.ttl) { accepted.push(index); last.set(event.id,event.at); }
});
return accepted;`,examples:[[{ttl:10,events:[{id:"a",at:0},{id:"a",at:9},{id:"a",at:10}]},[0,2]]],extra:[[{ttl:5,events:[{id:"a",at:0},{id:"b",at:0},{id:"a",at:1},{id:"b",at:5}]},[0,1,3]],[{ttl:0,events:[{id:"a",at:0},{id:"a",at:0}]},[0,1]],[{ttl:10,events:[]},[]]],hints:["Store last accepted time rather than last observed time.","Use >= at expiry.","Keep identity independent from delivery position."],why:["The window attaches to an accepted effect, not every retry. Extending the window on rejected retries could prevent an event from ever being accepted again under persistent retries.","The Map prevents one event ID from affecting another. Production retention can expire old entries once all future timestamps exceed their windows."],cost:"O(n) expected time and O(u) space for u distinct IDs."}),
  exercise({id:"event-subscription-lifecycle",title:"Subscriptions across enable and disable",track:"Events",tags:["lifecycle","cleanup"],modules:["events"],lessons:[8,24],task:"Simulate owner-scoped subscriptions during reload. Enabling an already enabled owner is a no-op, and disabling it removes only its own listeners.",rules:["Actions are enable(owner,listeners), disable(owner), or emit(event).", "Emit returns subscriber owner:name labels in owner enable order and listener order.","A re-enabled owner moves to the end of the owner ordering.","Return one array per emit."],input:"{actions:({kind:'enable';owner:string;listeners:{name:string;event:string}[]}|{kind:'disable';owner:string}|{kind:'emit';event:string})[]}",body:`const owners = new Map(), out = [];
for (const action of input.actions) {
  if (action.kind === "enable" && !owners.has(action.owner)) owners.set(action.owner,action.listeners);
  if (action.kind === "disable") owners.delete(action.owner);
  if (action.kind === "emit") out.push([...owners].flatMap(([owner,listeners])=>listeners.filter(l=>l.event===action.event).map(l=>owner+":"+l.name)));
}
return out;`,examples:[[{actions:[{kind:"enable",owner:"a",listeners:[{name:"join",event:"join"}]},{kind:"enable",owner:"a",listeners:[{name:"duplicate",event:"join"}]},{kind:"emit",event:"join"},{kind:"disable",owner:"a"},{kind:"emit",event:"join"}]},[["a:join"],[]]]],extra:[[{actions:[{kind:"enable",owner:"a",listeners:[]},{kind:"enable",owner:"b",listeners:[{name:"x",event:"x"}]},{kind:"disable",owner:"a"},{kind:"emit",event:"x"}]},[["b:x"]]],[{actions:[]},[]]],hints:["Use one ordered Map keyed by owner.","Guard enable instead of overwriting existing listeners.","Derive deliveries at emission time from active owners."],why:["Lifecycle ownership is the resource boundary. Clearing a global listener list on one plugin's disable would break other owners.","Map insertion order gives the required ordering, and delete followed by a new insertion naturally models re-enable."],cost:"O(a + emitted × active listeners) time; O(active listeners) space."}),
];
