import { pydanticModel } from "./author-python.ts";

export const pydanticProblems = [
  pydanticModel({ id: "purchase-model", title: "Validate a purchase before any side effect", tags: ["Pydantic", "constraints", "extra fields"], lessons: [20,21],
    task: "Define the purchase request accepted by the plugin's shop API. A valid model must reject unexpected client-supplied fields, whitespace-only SKUs and quantities beyond one inventory stack.",
    rules: ["sku is a stripped string of length 1..32.", "quantity is a strict integer in 1..64, defaulting to 1.", "Reject extra fields with extra='forbid'."],
    model: `class Request(BaseModel):
    model_config = ConfigDict(extra="forbid", str_strip_whitespace=True)
    sku: str = Field(min_length=1, max_length=32)
    quantity: int = Field(default=1, ge=1, le=64, strict=True)`,
    examples: [[{sku:" stone ",quantity:4},{ok:true,value:{sku:"stone",quantity:4}}], [{sku:"book"},{ok:true,value:{sku:"book",quantity:1}}]],
    extra: [[{sku:"stone",quantity:"4"},{ok:false,errors:[{loc:["quantity"],type:"int_type"}]}], [{sku:"stone",quantity:65},{ok:false,errors:[{loc:["quantity"],type:"less_than_equal"}]}], [{sku:"stone",price:0},{ok:false,errors:[{loc:["price"],type:"extra_forbidden"}]}], [{sku:"   "},{ok:false,errors:[{loc:["sku"],type:"string_too_short"}]}]],
    hints:["Use ConfigDict for both stripping and the extra-field policy.", "Pydantic normally coerces numbers; strict=True changes that boundary.", "The default must obey the same public contract as supplied values."],
    why:["The request model is an authorization boundary, not a convenient object constructor. Client fields such as price must never become trusted shop state.", "String normalization runs before the length constraint, so a whitespace-only SKU is rejected. Strict quantity validation also prevents booleans or numeric strings from being mistaken for a requested stack size."], cost:"O(length of sku + number of fields)." }),
  pydanticModel({ id:"coordinate-model",title:"Validate finite world coordinates",tags:["Pydantic","floats","bounds"],lessons:[20,21],task:"Model a teleport target. Coordinates must remain inside the world limits, and yaw must be normalized rather than silently accepted outside its canonical interval.",rules:["world is a nonempty string.","x and z are finite floats between -30000000 and 30000000.","y is a finite float between -64 and 320.","yaw defaults to 0 and is normalized to [0,360)."],
    model:`class Request(BaseModel):
    world: str = Field(min_length=1)
    x: float = Field(ge=-30000000, le=30000000, allow_inf_nan=False)
    y: float = Field(ge=-64, le=320, allow_inf_nan=False)
    z: float = Field(ge=-30000000, le=30000000, allow_inf_nan=False)
    yaw: float = Field(default=0, allow_inf_nan=False)
    @field_validator("yaw")
    @classmethod
    def normalize_yaw(cls, value):
        return value % 360`,
    examples:[[{world:"world",x:0,y:64,z:2,yaw:-90},{ok:true,value:{world:"world",x:0,y:64,z:2,yaw:270}}]],extra:[[{world:"w",x:30000001,y:64,z:0},{ok:false,errors:[{loc:["x"],type:"less_than_equal"}]}],[{world:"w",x:0,y:-65,z:0},{ok:false,errors:[{loc:["y"],type:"greater_than_equal"}]}],[{world:"w",x:-30000000,y:320,z:30000000,yaw:720},{ok:true,value:{world:"w",x:-30000000,y:320,z:30000000,yaw:0}}]],hints:["Reject non-finite numbers with allow_inf_nan=False.","Constraints and normalization belong in different declarations.","Python's modulo by a positive number handles negative yaw."],why:["Field constraints reject impossible teleport targets at the protocol boundary before a game-world lookup occurs.","A field validator returns the canonical yaw value. This gives storage, comparison and rendering one representation for an angle that can otherwise have infinitely many equivalent spellings."],cost:"O(1) validation." }),
  pydanticModel({id:"trade-invariant-model",title:"Cross-field trade invariants",hard:true,tags:["Pydantic","model validators","trades"],lessons:[21,28],task:"Validate a proposed trade before allocating locks or opening UI. The initiator and recipient must differ, and the offer must contain at least one positive amount.",rules:["initiator and recipient are nonempty strings.","coins is an integer >= 0; items is a list of positive integers.","Reject a self-trade and reject an empty offer with a model-level value_error.","Default coins to 0 and items to []."],model:`class Request(BaseModel):
    initiator: str = Field(min_length=1)
    recipient: str = Field(min_length=1)
    coins: int = Field(default=0, ge=0)
    items: list[Annotated[int, Field(gt=0)]] = Field(default_factory=list)
    @model_validator(mode="after")
    def check_offer(self):
        if self.initiator == self.recipient:
            raise ValueError("Self-trade is not allowed")
        if self.coins == 0 and not self.items:
            raise ValueError("The offer is empty")
        return self`,imports:"from typing import Annotated\n",examples:[[{initiator:"a",recipient:"b",items:[2]},{ok:true,value:{initiator:"a",recipient:"b",coins:0,items:[2]}}]],extra:[[{initiator:"a",recipient:"a",coins:1},{ok:false,errors:[{loc:[],type:"value_error"}]}],[{initiator:"a",recipient:"b"},{ok:false,errors:[{loc:[],type:"value_error"}]}],[{initiator:"a",recipient:"b",items:[0]},{ok:false,errors:[{loc:["items",0],type:"greater_than"}]}]],hints:["Use Annotated to constrain each list element.","An after model validator can inspect all successfully parsed fields.","Return self from a successful after validator."],why:["A field validator cannot naturally establish an invariant spanning initiator, recipient and the complete offer. An after model validator sees the validated aggregate.","Rejecting empty or self-directed trades before locking resources avoids creating impossible workflow states and unnecessary cleanup."],cost:"O(number of offered items)."}),
  pydanticModel({id:"api-alias-model",title:"Wire aliases without leaking internal names",tags:["Pydantic","aliases","serialization"],lessons:[19,21,22],task:"The JavaScript client sends playerId and displayName while Python services use snake_case. Accept either spelling but always serialize the internal model using snake_case in this exercise.",rules:["player_id is an integer > 0 with alias playerId.","display_name is a nonempty string with alias displayName.","Allow population by field name as well as alias.","Return the usual modelRunner output; model_dump uses internal field names."],model:`class Request(BaseModel):
    model_config = ConfigDict(populate_by_name=True)
    player_id: int = Field(alias="playerId", gt=0)
    display_name: str = Field(alias="displayName", min_length=1)`,examples:[[{playerId:7,displayName:"Alex"},{ok:true,value:{player_id:7,display_name:"Alex"}}]],extra:[[{player_id:8,display_name:"Sam"},{ok:true,value:{player_id:8,display_name:"Sam"}}],[{playerId:0,displayName:"A"},{ok:false,errors:[{loc:["playerId"],type:"greater_than"}]}],[{displayName:"A"},{ok:false,errors:[{loc:["playerId"],type:"missing"}]}]],hints:["alias changes input lookup and error locations.","Population by name is a separate configuration choice.","Serialization aliases are enabled with by_alias, which the supplied runner does not use."],why:["Aliases are an explicit wire-to-domain adapter rather than a reason to rename every internal Python field.","The public response policy can later choose by_alias=True. Keeping that decision explicit prevents generated clients and service code from drifting accidentally."],cost:"O(number of fields)."}),
  pydanticModel({id:"packet-discriminator-model",title:"Discriminate realtime event payloads",hard:true,tags:["Pydantic","discriminated unions","WebSocket"],lessons:[19,21,33],task:"A WebSocket envelope carries either a score update or a kick instruction. Validate the variant by its kind tag instead of guessing from whichever fields happen to exist.",rules:["Score has kind='score', player:string and delta:int.","Kick has kind='kick', player:string and reason:string.","The envelope has one event field discriminated by kind.","An unknown tag must produce union_tag_invalid; a missing tag produces union_tag_not_found."],imports:"from typing import Annotated, Literal, Union\n",model:`class Score(BaseModel):
    kind: Literal["score"]
    player: str
    delta: int
class Kick(BaseModel):
    kind: Literal["kick"]
    player: str
    reason: str
class Request(BaseModel):
    event: Annotated[Union[Score, Kick], Field(discriminator="kind")]`,examples:[[{event:{kind:"score",player:"a",delta:3}},{ok:true,value:{event:{kind:"score",player:"a",delta:3}}}]],extra:[[{event:{kind:"kick",player:"b",reason:"spam"}},{ok:true,value:{event:{kind:"kick",player:"b",reason:"spam"}}}],[{event:{kind:"unknown",player:"a"}},{ok:false,errors:[{loc:["event"],type:"union_tag_invalid"}]}],[{event:{player:"a"}},{ok:false,errors:[{loc:["event"],type:"union_tag_not_found"}]}]],hints:["Literal constrains each model's tag.","Attach Field(discriminator='kind') to the union.","An untagged union would attempt variants rather than select the declared one."],why:["Discriminated unions align protocol validation with TypeScript's tagged-union narrowing and a plugin state machine's explicit event kinds.","Pydantic can select the correct branch directly. That avoids ambiguous payloads and yields a clear error at the envelope when the tag is missing or unknown."],cost:"O(payload size) with constant-time tag selection."}),
  pydanticModel({id:"nested-party-model",title:"Nested party limits and unique members",hard:true,tags:["Pydantic","nested schemas","uniqueness"],lessons:[20,21],task:"Accept a party with at most four distinct player IDs. Validate each nested member before enforcing the aggregate uniqueness rule.",rules:["name is a nonempty string.","members contains 1..4 objects with player_id > 0 and ready:boolean default false.","Repeated player IDs cause a model-level value_error."],model:`class Member(BaseModel):
    player_id: int = Field(gt=0)
    ready: bool = False
class Request(BaseModel):
    name: str = Field(min_length=1)
    members: list[Member] = Field(min_length=1, max_length=4)
    @model_validator(mode="after")
    def distinct(self):
        if len({member.player_id for member in self.members}) != len(self.members):
            raise ValueError("Duplicate player")
        return self`,examples:[[{name:"miners",members:[{player_id:1},{player_id:2,ready:true}]},{ok:true,value:{name:"miners",members:[{player_id:1,ready:false},{player_id:2,ready:true}]}}]],extra:[[{name:"x",members:[]},{ok:false,errors:[{loc:["members"],type:"too_short"}]}],[{name:"x",members:[{player_id:1},{player_id:1}]},{ok:false,errors:[{loc:[],type:"value_error"}]}],[{name:"x",members:[{player_id:0}]},{ok:false,errors:[{loc:["members",0,"player_id"],type:"greater_than"}]}]],hints:["Use a nested BaseModel for members.","List size constraints apply to the list field.","Check duplicates after nested parsing so IDs have canonical integer representations."],why:["Nested models give error locations that identify the exact failing member and field.","The uniqueness invariant belongs to the party aggregate. Comparing normalized IDs after parsing prevents mixed string and integer spellings from bypassing deduplication."],cost:"O(m) time and O(m) space."}),
  pydanticModel({id:"decimal-price-model",title:"Exact currency precision",tags:["Pydantic","Decimal","money"],lessons:[21,25],task:"Define an exact price model for the shop backend. Binary floating-point values should not determine whether a purchase satisfies a two-decimal currency contract.",rules:["amount is Decimal >= 0 with at most 8 digits and at most 2 decimal places.","currency is the literal 'COIN', defaulting to 'COIN'.", "JSON serialization represents Decimal as a string."],imports:"from decimal import Decimal\nfrom typing import Literal\n",model:`class Request(BaseModel):
    amount: Decimal = Field(ge=0, max_digits=8, decimal_places=2)
    currency: Literal["COIN"] = "COIN"`,examples:[[{amount:"12.50"},{ok:true,value:{amount:"12.50",currency:"COIN"}}]],extra:[[{amount:"0.001"},{ok:false,errors:[{loc:["amount"],type:"decimal_max_places"}]}],[{amount:"-1"},{ok:false,errors:[{loc:["amount"],type:"greater_than_equal"}]}],[{amount:"1",currency:"USD"},{ok:false,errors:[{loc:["currency"],type:"literal_error"}]}]],hints:["Use Decimal instead of rounding float values yourself.","max_digits and decimal_places are field constraints.","A Literal is a closed currency vocabulary."],why:["A decimal contract preserves the text's base-10 quantity. Rounding an already imprecise float can silently change the requested monetary amount.","Restricting the currency tag prevents an amount denominated in one currency from being interpreted as another. Decimal's JSON string representation keeps exact precision through a JavaScript client."],cost:"O(number of decimal digits)."}),
  pydanticModel({id:"time-window-model",title:"Timezone-aware booking windows",hard:true,tags:["Pydantic","datetime","invariants"],lessons:[21,34],task:"Validate a raid booking whose end is after its start. Require timezone-aware timestamps so server-local timezone configuration cannot change ordering.",rules:["start and end are AwareDatetime fields.","end must be strictly later than start.","Reject equal or reversed windows with a model-level value_error.","Keep Pydantic's JSON datetime serialization."],imports:"from pydantic import AwareDatetime\n",model:`class Request(BaseModel):
    start: AwareDatetime
    end: AwareDatetime
    @model_validator(mode="after")
    def ordered(self):
        if self.end <= self.start:
            raise ValueError("End must follow start")
        return self`,examples:[[{start:"2026-10-01T12:00:00Z",end:"2026-10-01T13:00:00Z"},{ok:true,value:{start:"2026-10-01T12:00:00Z",end:"2026-10-01T13:00:00Z"}}]],extra:[[{start:"2026-10-01T12:00:00",end:"2026-10-01T13:00:00Z"},{ok:false,errors:[{loc:["start"],type:"timezone_aware"}]}],[{start:"2026-10-01T12:00:00Z",end:"2026-10-01T12:00:00Z"},{ok:false,errors:[{loc:[],type:"value_error"}]}],[{start:"2026-10-01T12:00:00+02:00",end:"2026-10-01T09:59:00Z"},{ok:false,errors:[{loc:[],type:"value_error"}]}]],hints:["AwareDatetime rejects naive inputs at the field boundary.","Compare datetime values rather than timestamp strings.","Offsets can differ while representing the same instant."],why:["Lexicographic timestamp comparison does not compare instants when offsets differ. A timezone-aware datetime comparison does.","The aggregate validator then checks the actual window invariant; a valid format alone says nothing about whether the booking has positive duration."],cost:"O(1) for bounded timestamp strings."}),
  pydanticModel({id:"slug-normalization-model",title:"Canonical identifiers with a before validator",tags:["Pydantic","normalization","validators"],lessons:[21,34],task:"Normalize a human-readable arena identifier before applying its slug grammar. Accept spaces and uppercase letters as input, but only one canonical slug reaches storage.",rules:["slug is a string matching ^[a-z0-9]+(?:-[a-z0-9]+)*$ with length 1..40.","Strip, lowercase, and replace each whitespace run with one hyphen before validation.","Other punctuation remains invalid."],imports:"import re\n",model:`class Request(BaseModel):
    slug: str = Field(min_length=1, max_length=40, pattern=r"^[a-z0-9]+(?:-[a-z0-9]+)*$")
    @field_validator("slug", mode="before")
    @classmethod
    def normalize(cls, value):
        if isinstance(value, str):
            return re.sub(r"\\s+", "-", value.strip().lower())
        return value`,examples:[[{slug:"  Sky   Arena "},{ok:true,value:{slug:"sky-arena"}}]],extra:[[{slug:"a/b"},{ok:false,errors:[{loc:["slug"],type:"string_pattern_mismatch"}]}],[{slug:"   "},{ok:false,errors:[{loc:["slug"],type:"string_too_short"}]}],[{slug:"MINER-2"},{ok:true,value:{slug:"miner-2"}}]],hints:["A before validator receives the raw value.","Normalize only strings; let the field reject other types.","Normalize whitespace without deleting arbitrary punctuation."],why:["Normalization before grammar validation permits intentional human input conveniences without relaxing the stored identifier contract.","Deleting every invalid character could turn distinct malicious or mistaken names into the same identifier. The validator transforms only the explicitly documented input equivalences."],cost:"O(n) time and space."}),
  pydanticModel({id:"immutable-session-model",title:"Frozen session configuration with safe defaults",tags:["Pydantic","immutability","default factories"],lessons:[21,28,31],task:"Declare a frozen session configuration. Each instance owns its own list of scopes; missing input is not the same as a shared mutable default in service code.",rules:["session_id is a nonempty string.","scopes defaults to a fresh empty list of strings.","ttl is an integer in 1..3600, default 300.","Set frozen=True and extra='forbid'."],model:`class Request(BaseModel):
    model_config = ConfigDict(frozen=True, extra="forbid")
    session_id: str = Field(min_length=1)
    scopes: list[str] = Field(default_factory=list)
    ttl: int = Field(default=300, ge=1, le=3600)`,examples:[[{session_id:"s"},{ok:true,value:{session_id:"s",scopes:[],ttl:300}}]],extra:[[{session_id:"s",scopes:["shop.read"],ttl:3600},{ok:true,value:{session_id:"s",scopes:["shop.read"],ttl:3600}}],[{session_id:"s",ttl:0},{ok:false,errors:[{loc:["ttl"],type:"greater_than_equal"}]}],[{session_id:"s",admin:true},{ok:false,errors:[{loc:["admin"],type:"extra_forbidden"}]}],[{__modelProbe:{data:{session_id:"s"},field:"ttl",value:1}},{frozen:true,independent_defaults:true},"Frozen assignment and default ownership"]],hints:["Use ConfigDict to declare model-level policy.","Use default_factory for list construction.","Frozen prevents field reassignment; nested collections still need careful ownership."],why:["A configuration contract can reject accidental assignment after construction while preserving a predictable serialization shape.","Frozen models are not deeply immutable: scopes is still a list. The editorial distinction matters when sharing the model with caches or concurrent consumers; use immutable nested types where that ownership model requires them."],cost:"O(number of scopes)."}),
  pydanticModel({id:"uuid-set-model",title:"Canonical player IDs and stable deduplication",tags:["Pydantic","UUID","deduplication"],lessons:[21,34],task:"Accept UUID player identifiers and deduplicate canonical values while preserving their first occurrence. Equivalent hexadecimal spellings must not create duplicate recipients.",rules:["players is a list of UUID values, with at most 100 supplied entries.","A field validator removes duplicate UUIDs in first-seen order.","Serialize canonical hyphenated lowercase UUID strings."],imports:"from uuid import UUID\n",model:`class Request(BaseModel):
    players: list[UUID] = Field(max_length=100)
    @field_validator("players")
    @classmethod
    def distinct(cls, values):
        return list(dict.fromkeys(values))`,examples:[[{players:["00000000-0000-0000-0000-000000000001","00000000000000000000000000000001"]},{ok:true,value:{players:["00000000-0000-0000-0000-000000000001"]}}]],extra:[[{players:[]},{ok:true,value:{players:[]}}],[{players:["not-a-uuid"]},{ok:false,errors:[{loc:["players",0],type:"uuid_parsing"}]}],[{players:["00000000-0000-0000-0000-000000000002","00000000-0000-0000-0000-000000000001"]},{ok:true,value:{players:["00000000-0000-0000-0000-000000000002","00000000-0000-0000-0000-000000000001"]}}]],hints:["Let UUID parsing establish canonical identity first.","An after field validator receives UUID objects.","dict.fromkeys preserves first-seen ordering."],why:["Deduplicating raw strings would leave multiple spellings of the same UUID in a recipient list. Parsing first makes equality semantic.","Stable deduplication preserves an operator's requested delivery order while bounding input size before expensive downstream work."],cost:"O(n) expected time and O(n) space."}),
  pydanticModel({id:"computed-total-model",title:"Computed totals and secret-free serialization",hard:true,tags:["Pydantic","computed fields","secrets"],lessons:[21,25,30],task:"Model a quote without trusting a client-supplied total. The serialized response must include a server-derived total and must exclude the service-only secret.",rules:["quantity is an integer >= 1 and unit_price is an integer >= 0.","internal_secret is a string excluded from serialization.","A computed_field total equals quantity * unit_price.","Reject a supplied total or any extra field."],imports:"from pydantic import computed_field\n",model:`class Request(BaseModel):
    model_config = ConfigDict(extra="forbid")
    quantity: int = Field(ge=1)
    unit_price: int = Field(ge=0)
    internal_secret: str = Field(exclude=True)
    @computed_field
    @property
    def total(self) -> int:
        return self.quantity * self.unit_price`,examples:[[{quantity:3,unit_price:7,internal_secret:"token"},{ok:true,value:{quantity:3,unit_price:7,total:21}}]],extra:[[{quantity:1,unit_price:0,internal_secret:"x"},{ok:true,value:{quantity:1,unit_price:0,total:0}}],[{quantity:1,unit_price:2,internal_secret:"x",total:0},{ok:false,errors:[{loc:["total"],type:"extra_forbidden"}]}],[{quantity:0,unit_price:2,internal_secret:"x"},{ok:false,errors:[{loc:["quantity"],type:"greater_than_equal"}]}]],hints:["Make total a computed property, not an input field.","Field(exclude=True) controls serialization of internal_secret.","Use extra='forbid' to reject attempts to inject a computed value."],why:["The server owns derived prices. A computed field keeps the formula in one place and prevents an independently stored total from drifting from its inputs.","Excluding service-only data is an explicit output contract. Returning every attribute of an internal model would risk leaking credentials even when validation succeeded."],cost:"O(1) calculation and bounded serialization."}),
];
