import { exercise } from "./author.ts";
import type { Json } from "./types.ts";
const f=(props:Json,actions:Json[],paths:string[])=>({props,actions,paths});
const click={kind:"click",slot:0};
const rr=(props:Json)=>({kind:"rerender",props});
function r(id:string,title:string,body:string,extra:string,rules:string[],cases:[Json,Json][],lessons:number[],why:string){return exercise({id,title,track:"React native UI",mode:"react",hard:true,modules:["ui"],lessons,tags:["React","advanced","lifecycle"],task:title+" using the actual Graaly reconciler. Implement the components and module-level helpers rather than substituting a precomputed snapshot.",rules,input:"Native actions and rerenders use the same test transport as the production SDK.",imports:'import React, {useState,useEffect,useRef,useSyncExternalStore,useTransition,useOptimistic,Suspense,lazy}from"react";\nimport{Inventory,Item,Message,Tab,createRoot,createPortal}from"@graaly/react";\n'+extra,body,examples:cases.slice(0,1),extra:cases.slice(1),hints:[rules[0],"Separate component identity from the values passed through props.",why],why:[why,"The renderer test flushes actual React work and checks native output after the supplied actions, including rejected and restarted flows."],cost:"O(component tree + published data)."});}
export const advancedReactProblems=[
r("react-error-boundary","Recover a native subtree through an Error Boundary",'return <Boundary>{input.fail?<Broken/>:<Message id="ok">OK</Message>}</Boundary>;',`class Boundary extends React.Component{
 constructor(props){super(props);this.state={failed:false};}
 static getDerivedStateFromError(){return {failed:true};}
 render(){return this.state.failed?<Message id="fallback">Unavailable</Message>:this.props.children;}
}
function Broken(){throw new Error("Unavailable feature");}`,["A failing child renders Message Unavailable.","A successful child renders Message OK.","A caught failure remains in fallback until the boundary remounts."],[[f({fail:false},[],["messages.0.text"]),{"messages.0.text":"OK"}],[f({fail:true},[],["messages.0.text"]),{"messages.0.text":"Unavailable"}],[f({fail:true},[rr({fail:false})],["messages.0.text"]),{"messages.0.text":"Unavailable"}]],[14,17],"An Error Boundary catches render failures inside its subtree and owns the fallback state. Catching an event handler's error is a different operation."),
r("react-lazy-suspense","Resolve a lazy component behind Suspense",'return <Suspense fallback={<Message id="loading">Loading</Message>}><Loaded value={input.value}/></Suspense>;',`const Loaded=lazy(()=>Promise.resolve({default:function Ready({value}){return <Message id="ready">{"Ready "+value}</Message>;}}));`,["Load a component through React.lazy.","Use Message Loading as Suspense fallback.","The resolved component renders Ready followed by current value."],[[f({value:"a"},[],["messages.0.text"]),{"messages.0.text":"Ready a"}],[f({value:"a"},[rr({value:"b"})],["messages.0.text"]),{"messages.0.text":"Ready b"}],[f({value:0},[],["messages.0.text"]),{"messages.0.text":"Ready 0"}]],[14],"Lazy loading is a module-resolution state owned by React. Suspense handles a pending component without turning loading into a domain error."),
r("react-transition","Publish a completed nonurgent native update",'const [value,setValue]=useState(0);const [pending,start]=useTransition();return <Inventory title={String(value)} rows={1}><Item slot={0} material="BOOK" name={pending?"Pending":"Ready"} onClick={()=>start(()=>setValue(n=>n+input.step))}/></Inventory>;',"",["Initial value is zero.","Each click starts a transition that adds current step.","After flushed work the item says Ready."],[[f({step:2},[click],["inventory.title","inventory.items.0.name"]),{"inventory.title":"2","inventory.items.0.name":"Ready"}],[f({step:2},[click,rr({step:5}),click],["inventory.title"]),{"inventory.title":"7"}],[f({step:0},[click],["inventory.title"]),{"inventory.title":"0"}]],[15],"A transition marks nonurgent render work while the accepted state still follows ordinary updater semantics. Pending state describes rendering, not transaction success."),
r("react-optimistic","Reconcile an optimistic action with server acceptance",'const [count,setCount]=useState(0);const [optimistic,add]=useOptimistic(count,(n,delta)=>n+delta);const [,start]=useTransition();return <Inventory title={String(optimistic)} rows={1}><Item slot={0} material="EMERALD" name="Buy" onClick={()=>start(async()=>{add(1);await Promise.resolve();if(input.accepted)setCount(n=>n+1);})}/></Inventory>;',"",["A click optimistically adds one inside an async transition.","Only accepted=true commits the count.","Rejection rolls back speculative state."],[[f({accepted:true},[click],["inventory.title"]),{"inventory.title":"1"}],[f({accepted:false},[click],["inventory.title"]),{"inventory.title":"0"}],[f({accepted:true},[click,click],["inventory.title"]),{"inventory.title":"2"}]],[15,25],"Optimistic state is a temporary projection over committed state. On rejection the projection disappears; manually storing the optimistic increment as committed data would make rollback incorrect."),
r("react-custom-hook","Extract a reusable bounded counter Hook",'const [value,increment]=useBounded(input.initial,input.max);return <Inventory title={String(value)} rows={1}><Item slot={0} material="STONE" name="Add" onClick={increment}/></Inventory>;',`function useBounded(initial,max){const [value,setValue]=useState(()=>Math.max(0,Math.min(max,initial)));return [Math.min(value,max),()=>setValue(n=>Math.min(max,n+1))];}`,["Custom Hook owns count initialized in [0,max].","Increment is capped by the current max prop.","Lowering max immediately bounds published output."],[[f({initial:1,max:2},[click,click],["inventory.title"]),{"inventory.title":"2"}],[f({initial:8,max:3},[],["inventory.title"]),{"inventory.title":"3"}],[f({initial:3,max:5},[rr({initial:3,max:1})],["inventory.title"]),{"inventory.title":"1"}]],[12],"A custom Hook extracts stateful behavior while each component call retains independent state. Current limits remain reactive inputs rather than frozen initialization values."),
r("react-external-store","Subscribe to a stable external store snapshot",'const count=useSyncExternalStore(subscribe,getSnapshot,getSnapshot);return <Inventory title={String(count)} rows={1}><Item slot={0} material="STONE" name="Add" onClick={increment}/></Inventory>;',`let value=0;const listeners=new Set();
function getSnapshot(){return value;}
function subscribe(listener){listeners.add(listener);return()=>listeners.delete(listener);}
function increment(){value++;for(const listener of listeners)listener();}`,["The external store starts at zero.","Subscribe via useSyncExternalStore and return an unsubscribe function.","Each click updates the store and notifies listeners."],[[f({},[click],["inventory.title"]),{"inventory.title":"1"}],[f({},[click,click],["inventory.title"]),{"inventory.title":"2"}],[f({},[click,rr({}),click],["inventory.title"]),{"inventory.title":"2"}]],[12,27],"External store snapshots must be stable until the store changes. The subscription owns cleanup and notification rather than an effect that reads a mutable object opportunistically."),
r("react-cross-player-portal","Render an owned surface through a cross-player portal",'return <><Tab header="Owner"/>{createPortal(<Inventory title={input.title} rows={1}><Item slot={0} material="BOOK" name={input.name}/></Inventory>,friend)}</>;',`const friend=createRoot({id:"friend",name:"Friend"});`,["Keep a Tab header Owner in the primary player's root.","Portal the inventory to Friend's separate root.","The inventory uses current title/name props."],[[f({title:"Trade",name:"Offer"},[],["tab.header","inventory","native.Friend.inventory.title","native.Friend.inventory.items.0.name"]),{"tab.header":"Owner","inventory":null,"native.Friend.inventory.title":"Trade","native.Friend.inventory.items.0.name":"Offer"}],[f({title:"A",name:"a"},[rr({title:"B",name:"b"})],["native.Friend.inventory.title"]),{"native.Friend.inventory.title":"B"}],[f({title:"Empty",name:""},[],["native.Friend.inventory.items.0.name"]),{"native.Friend.inventory.items.0.name":""}]],[16],"A portal shares the parent React tree while publishing to a separately owned player surface. It changes destination, not business ownership or component identity."),
r("react-boundary-reset","Reset an error fallback only on a new session key",'return <Boundary key={input.session}>{input.fail?<Broken/>:<Message id="ok">OK</Message>}</Boundary>;',`class Boundary extends React.Component{
 constructor(props){super(props);this.state={failed:false};}
 static getDerivedStateFromError(){return {failed:true};}
 render(){return this.state.failed?<Message id="fallback">Unavailable</Message>:this.props.children;}
}
function Broken(){throw new Error("Unavailable");}`,["The boundary remains failed while the session key is unchanged.","A new session key remounts it and can recover.","Use the same fallback Message Unavailable."],[[f({session:"a",fail:true},[rr({session:"a",fail:false})],["messages.0.text"]),{"messages.0.text":"Unavailable"}],[f({session:"a",fail:true},[rr({session:"b",fail:false})],["messages.0.text"]),{"messages.0.text":"OK"}],[f({session:"a",fail:false},[],["messages.0.text"]),{"messages.0.text":"OK"}]],[5,14,28],"An error fallback has state and identity. A deliberate session reset permits recovery without repeatedly retrying a still-broken subtree on every render."),
];
